baseURL: https://lollar.github.io
languageCode: en-us
title: Lollar Codes
theme: PaperMod
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

menu:
  main:
    - name: About
      url: about/
      weight: 5
    - name: Contact
      url: contact/
      weight: 7
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - name: Categories
      url: categories/
      weight: 10
